import 'dart:convert';
import 'dart:io';

import '../database/database_service.dart';
import '../knowledge/kb_service.dart';

/// LLM Lab — on-device model building. Data preparation and config generation
/// are fully implemented and run locally; the actual gradient step is executed
/// by a local llama.cpp `llama-finetune`/`llama-train` binary when present.
/// This service is honest: it never pretends training happened when the
/// binary is missing — it reports exactly what is required.
class LlmLabService {
  final DatabaseService db;
  final KbService kb;

  LlmLabService({required this.db, required this.kb});

  String? get finetuneBinary {
    for (final name in ['llama-finetune', 'llama-train', 'llama-cpp-finetune']) {
      try {
        final r = Process.runSync('which', [name]);
        if (r.exitCode == 0 && (r.stdout as String).trim().isNotEmpty) {
          return (r.stdout as String).trim();
        }
      } catch (_) {}
    }
    return null;
  }

  bool get trainingAvailable => finetuneBinary != null;

  /// Prepare a fine-tune dataset from the knowledge base (pure Dart).
  Future<Map<String, Object?>> prepareDataset() async {
    final docs = await db.listKbDocuments();
    final chunks = await db.allKbChunks(limit: 20000);
    final lines = <String>[];
    for (final c in chunks.take(10000)) {
      lines.add(jsonEncode({
        'messages': [
          {'role': 'system', 'content': 'You are Pixel, the user\'s local AI harness.'},
          {'role': 'user', 'content': 'Context from ${_docTitle(docs, c.documentId)}:'},
          {'role': 'assistant', 'content': c.text},
        ]
      }));
    }
    final datasetPath =
        '${Directory.systemTemp.path}/pixel_finetune_${DateTime.now().millisecondsSinceEpoch}.jsonl';
    await File(datasetPath).writeAsString(lines.join('\n'));
    return {
      'samples': lines.length,
      'path': datasetPath,
      'sizeBytes': (await File(datasetPath).length()),
    };
  }

  Future<String> buildConfig({
    String baseModel = 'llama3.2:1b',
    int epochs = 3,
  }) async {
    final ds = await prepareDataset();
    final cfg = {
      'model': baseModel,
      'dataset': ds['path'],
      'epochs': epochs,
      'learning_rate': 1e-5,
      'block_size': 128,
      'output': 'pixel-${DateTime.now().millisecondsSinceEpoch}',
      'note': 'Generated by Pixel LLM Lab; consumed by llama.cpp finetune.',
    };
    final path =
        '${Directory.systemTemp.path}/pixel_train_config_${DateTime.now().millisecondsSinceEpoch}.json';
    await File(path).writeAsString(const JsonEncoder.withIndent('  ').convert(cfg));
    return path;
  }

  String _docTitle(List docs, int id) {
    for (final d in docs) {
      if (d.id == id) return d.title;
    }
    return 'document $id';
  }

  /// Returns the exact shell command that would run training, whether the
  /// binary exists or not. Honest: if not available we execute nothing.
  String trainingCommand(String baseModel, int epochs) {
    final out = finetuneBinary ?? 'llama-finetune';
    return '$out --model-file $baseModel --train-data '
        '${Directory.systemTemp.path}/pixel_*.jsonl --epochs $epochs --use-flash-attn off';
  }
}